name: CI

on: #Events
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    # runs-on: ubuntu-latest
    runs-on: 
      - self-hosted
      - kubeflow
    steps:          
      - name: Check out
        # uses: actions/checkout@v2
        uses: actions/checkout@v3

      - name: Docker Login
        # uses: docker/login-action@v1.8.0
        uses: docker/login-action@v3     
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build Images
        run: |
          docker build kubeflow_pipeline/0_data -t qorehd222/mnist-pre-data
          docker push qorehd222/mnist-pre-data
          docker build kubeflow_pipeline/1_validate_data -t qorehd222/mnist-val-data
          docker push qorehd222/mnist-val-data
          docker build kubeflow_pipeline/2_train_model -t qorehd222/mnist-train-model
          docker push qorehd222/mnist-train-model
          docker build kubeflow_pipeline/3_embedding -t qorehd222/mnist-embedding
          docker push qorehd222/mnist-embedding
          docker build kubeflow_pipeline/4_train_faiss -t qorehd222/mnist-train-faiss
          docker push qorehd222/mnist-train-faiss
          docker build kubeflow_pipeline/5_analysis_model -t qorehd222/mnist-analysis
          docker push qorehd222/mnist-analysis
          docker build kubeflow_pipeline/6_deploy -t qorehd222/mnist-deploy
          docker push qorehd222/mnist-deploy
      
      - name: Slack Notification
        if: always()
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_ICON_EMOJI: ':bell:'
          SLACK_CHANNEL: mnist-project
          SLACK_MESSAGE: 'Build/Push Images :building_construction: - ${{job.status}}'
          SLACK_USERNAME: Github
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}

